update

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -8,7 +8,6 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     strategy:
@@ -24,7 +23,14 @@ jobs:
         cache: 'npm'
     - run: npm ci
     - run: npm run build --if-present
-    - run: npm test -- --passWithNoTests
+
+    # Check if the build folder exists
+    - name: Check if build folder exists
+      run: |
+        if [ ! -d "build" ]; then
+          echo "Error: Build folder does not exist. Make sure the build step runs successfully."
+          exit 1
+        fi
 
     # Set Git user identity
     - name: Set Git user identity
@@ -42,7 +48,7 @@ jobs:
         git commit --allow-empty -m "Clean branch"
         git push origin gh-pages
 
-    # Deploy
+    # Deploy to GitHub Pages
     - name: Deploy
       uses: JamesIves/github-pages-deploy-action@v4
       with:
